//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAutoJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Car_History = new HashSet<Car_History>();
        }
    
        public int CarID { get; set; }
        public string RegNumber { get; set; }
        public string Country { get; set; }
        public Nullable<int> CarOwnerId { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
    
        public virtual CarOwner CarOwner { get; set; }
        public virtual ICollection<Car_History> Car_History { get; set; }
    }
}
