//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAutoJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarOwner
    {
        public CarOwner()
        {
            this.Car = new HashSet<Car>();
            this.CarOwner_History = new HashSet<CarOwner_History>();
        }
    
        public int CarOwnerID { get; set; }
        public Nullable<System.DateTime> FirstLicenseDate { get; set; }
        public string MaritalStatus { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string HairColor { get; set; }
    
        public virtual ICollection<Car> Car { get; set; }
        public virtual ICollection<CarOwner_History> CarOwner_History { get; set; }
        public virtual Userr Userr { get; set; }
    }
}
