//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAutoJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_History
    {
        public int MessageID { get; set; }
        public Nullable<int> RecieverId { get; set; }
        public Nullable<System.DateTime> DateViewed { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
