//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAutoJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        public Userr()
        {
            this.Message = new HashSet<Message>();
        }
    
        public int UserrID { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
        public string Email { get; set; }
        public Nullable<int> sn_ID { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    
        public virtual CarOwner CarOwner { get; set; }
        public virtual ICollection<Message> Message { get; set; }
    }
}
